i18n/en.pot, package.json, src/components/App.jsx, src/components/app/App.tsx, src/components/app/themes/dhis2.theme.js, src/components/settings/Settings.tsx, src/components/settings/SettingsFields.tsx, src/logic/settings.ts, src/types/d2.d.ts, yarn.lock
Closes #4
Settings button temporality in the top-right corner, we can discuss positioning on the next PR, here it's just the settings popup without any use in the app.
Notes to the reviewer:
- Button cancel does not reset the settings, that's on the next PR, when the component logic is integrated with main page.
=> Settings dialog

src/components/App.jsx
=> Show import feedkback message inline

public/app-config-default.json, public/app-config.json, public/index.html
=> add feedback infrastructure

src/webapp/logic/sheetBuilder.js, src/webapp/logic/sheetImport.js
* **Issue:** Closes #42
- Add support for validation on sheet builder
- Add support for reading values on sheet import
- I followed the style of the old code, we might improve it on a later stage
=> [Feature] Add boolean and yes only validations

package.json, src/data/InstanceDhisRepository.ts, src/webapp/components/template-selector/TemplateSelector.tsx, yarn.lock
- Add level and group filters 
- Split ``/events`` call by categories due to DHIS2 bug
- Add catch clause for network operations in events (detect 409 if user does not have permission to read data but do not fail, app just does not populate)
=> [Fix] Changes requested for patch release

src/webapp/logic/sheetBuilder.js, src/webapp/utils/excel.js
=> [Fix] Change error message for missing organisation unit

.eslintrc.js, i18n/en.pot, i18n/es.po, i18n/fr.po, src/webapp/components/theme-list/ThemeListTable.tsx
- Add ColorScale to ThemeListTable
=> [Feature] Add ColorScale to theme list table

i18n/en.pot, i18n/es.po, i18n/fr.po, src/CompositionRoot.ts, src/data/InstanceDhisRepository.ts, src/domain/entities/DataForm.ts, src/domain/usecases/ListDataFormsUseCase.ts, src/webapp/components/template-selector/TemplateSelector.tsx, src/webapp/pages/landing-page/LandingPage.jsx
* **Issue:** Closes #87
- Ensure programs/dataSets are filtered by ``metadata`` visible to them
- Hide populate checkbox if user does not have read permissions on a given dataSet/program
- Not sure if we want to even limit it more and instead of metadata visible to them use the read permission too
- Should we ensure the user has write permissions before uploading a template?
- Created issue https://github.com/EyeSeeTea/d2-api/issues/43
=> [Feature] Review user permissions

package.json, src/domain/usecases/DownloadTemplateUseCase.ts, src/webapp/components/template-selector/TemplateSelector.tsx, src/webapp/pages/download-template/DownloadTemplatePage.tsx, src/webapp/pages/import-template/ImportTemplatePage.tsx, yarn.lock
* **Issue:** Closes #98
* https://github.com/EyeSeeTea/d2-ui-components/pull/160
- See card #98
=> [Fix] Misc changes from review

src/webapp/pages/import-template/ImportTemplatePage.tsx
=> [Fix] Duplicate check in aggregated

i18n/en.pot, i18n/es.po, i18n/fr.po, package.json, src/data/InstanceDhisRepository.ts, src/webapp/components/drawer/Drawer.tsx, src/webapp/components/template-selector/TemplateSelector.tsx, src/webapp/components/theme-list/ThemeListTable.tsx, src/webapp/logic/settings.ts, src/webapp/pages/root/RootPage.tsx, yarn.lock
* **Issue:** Closes #119
* **Issue:** Closes #120
* **Issue:** Closes #121
* https://github.com/EyeSeeTea/d2-ui-components/pull/163
- Add "ALL" model option
- Do not prefill org units if checkbox not selected
- Keep OU Group and Level always visible
=> [Feature] Improvements

i18n/en.pot, i18n/es.po, i18n/fr.po, package.json, src/data/InstanceDhisRepository.ts, src/test/DownloadTemplatePage.spec.tsx, src/test/ImportTemplatePage.spec.tsx, src/test/SettingsPage.spec.tsx, src/webapp/components/settings/SettingsFields.tsx, src/webapp/components/template-selector/TemplateSelector.tsx, src/webapp/pages/import-template/ImportTemplatePage.tsx
* **Issue:** Closes #123 
* **Issue:** Closes #124
-
=> [Fix] Rename titles

src/test/mocks/server.ts, src/webapp/logic/settings.ts, src/webapp/logic/sheetImport.js
* **Issue:** Closes #132, #133
- Filter `identifiable` for user does not work, use `id` instead. JIRA report: https://jira.dhis2.org/browse/DHIS2-9326
- Comment out coordinates checking (needs refactor)
- Formulas with result 0 have no cell.result, add a case for this scenario.
=> Fix users load (2.34) + programs import (coordinates/empty formulas)

i18n/en.pot, i18n/es.po, i18n/fr.po, i18n/pt.po, src/data/Dhis2TrackedEntityInstances.ts, src/domain/entities/Template.ts, src/domain/usecases/ImportTemplateUseCase.ts, src/types/d2-api.ts, src/webapp/components/template-selector/TemplateSelector.tsx, src/webapp/logic/sheetBuilder.js, src/webapp/pages/download-template/DownloadTemplatePage.tsx, src/webapp/pages/import-template/ImportTemplatePage.tsx
=> [Feature] Populate custom templates

i18n/en.pot, i18n/es.po, i18n/fr.po, i18n/pt.po, src/webapp/logic/sheetBuilder.js
* **Issue:** Closes #170
- We didn't notice that creation of template and populate are on different steps, so we don't know the number of TEIs in advance (to make N + 1000). For now, set simply to 1000, let me know if that's not acceptable.
For the record, there are complex things that can be done:
https://stackoverflow.com/a/11243464/188031
But, for once, it does not work on libreoffice.
=> Limit max teis rows validations

src/data/ExcelPopulateRepository.ts, src/data/templates/TrackerProgramGenerated.01.ts, tsconfig.json
* **Issue:** Closes #165
- Removed `@cache` on `readCell.` We'll review with @SferaDev whether to re-instate it somehow or remove it altogether.
=> Fix file 2nd load on drop-zone

src/CompositionRoot.ts, src/data/Dhis2Import.ts, src/data/Dhis2TrackedEntityInstances.ts, src/data/InstanceDhisRepository.ts, src/domain/helpers/ExcelBuilder.ts, src/domain/helpers/ExcelReader.ts, src/domain/repositories/InstanceRepository.ts, src/domain/usecases/DownloadCustomTemplateUseCase.ts, src/domain/usecases/DownloadTemplateUseCase.ts
=> Fix getProgramPackage events variable name

src/data/Dhis2TrackedEntityInstances.ts
* **Issue:** Closes #187
- We already had a logic to fall back to true/false for boolean for data values. Use the same code for attributeValues.
=> Use in attributeValues same logic than dataValues (fixes boolean values)

i18n/en.pot, i18n/es.po, i18n/fr.po, i18n/pt.po, src/data/Dhis2RelationshipTypes.ts, src/data/Dhis2TrackedEntityInstances.ts
* **Issue:** Closes https://github.com/EyeSeeTea/Bulk-Load/pull/194#issuecomment-729519980
=> Fix TEI saving

src/domain/usecases/ImportTemplateUseCase.ts
=> [Fix] Override org unit when deleting existing values

package.json, src/data/StorageConstantRepository.ts
=> [Fix] Add default value to constant

i18n/en.pot, i18n/es.po, i18n/fr.po, i18n/pt.po, package.json, src/data/ConfigWebRepository.ts, src/domain/entities/AppSettings.ts, src/domain/usecases/ImportTemplateUseCase.ts, src/webapp/components/settings/SettingsFields.tsx, src/webapp/logic/settings.ts, src/webapp/pages/import-template/ImportTemplatePage.tsx
* **Issue:** CU-bpu3w2
- Add new setting persisted to dataStore
- Add new dropdown to enable/disable the setting
- Add logic to ignore duplicate check on both old/new logic
=> [Feature] Allow disabling duplicate check

i18n/es.po, i18n/fr.po, i18n/pt.po
- http://who-dev.essi.upc.edu:8083/issues/4025
- http://who-dev.essi.upc.edu:8083/issues/4026
- Fix translations
=> [Fix] Wrong translations due fuzzy automation

src/domain/usecases/ImportTemplateUseCase.ts
* **Issue:** Closes https://app.clickup.com/t/cpwa2h
- Same login in import usecase than old code in react component
=> Fix duplicated entries on import use case

src/data/ExcelPopulateRepository.ts, src/domain/helpers/ExcelReader.ts, src/webapp/logic/sheetImport.js
- https://app.clickup.com/t/c6u6bk
- Improve reading of dates
=> [Fix] Improve date and time handling

src/data/InstanceDhisRepository.ts, src/domain/entities/DataForm.ts, src/domain/usecases/ImportTemplateUseCase.ts, src/test/mocks/server.ts
- https://app.clickup.com/t/kqbk5k
- Bring-back option set and boolean transforms from old code
=> [Feature] Bring back option set transform

docs/nhwa/builder-module-8.js
- https://app.clickup.com/t/h91uhe
- Update template, builder and config
Module 8 Custom Form:
```html
<script type="text/javascript">
var yespartialno = [
"tKr3k3lbnJJ",
"ROVoulCcT0j",
"yqQBUxeuga4",
"tdwemEgGckz",
"wDaqByzsz7p",
"HgQ76w0VONy",
"f87mpByuPub",
"RHokurJAbjS",
"w8SWd1reRm8",
"IidAimBSgEf",
"q8CUMlpFLtJ",
"hR7B1ITcCMe",
"qNxAIa6jvmm",
"FZYvE3Jdf8L",
"wnjnfKvWllg",
"YQOr9kwr5k3"
];
var yesno = [];
var categoryIssues = ["I93t0K7b1oN", "Xgr3PJxcWfJ", "Y7EAGQA1bfv"];
var comments = [
"jlJcFRt3mmg",
"rYm7I91K6Je",
"PBUMZvqh0r2",
"xtrKmZJKljq",
"R6JXOAVTsay",
"risbLwkLwW5",
"oLpoOT6tO7g",
"RM1vy8bSPE8",
"jieOOtItEQg",
"tASpRJWiyvN",
"aAaUMHvUPv1",
"mwwpy9cyOGy",
"AK5r5VIXYOW",
"QuUK6IgR9oZ",
"bGA2GtwhrC9",
"cWUu9JeMtg7",
"ZRiwfBSthk1",
"jOP1khGwck2"
];
var percentages = …
```
=> [Feature] Update NHWA Module 8 script

i18n/en.pot, i18n/es.po, i18n/fr.po, i18n/pt.po, i18n/ru.po, package.json, src/domain/entities/Template.ts, src/domain/helpers/ExcelBuilder.ts, src/domain/usecases/ImportTemplateUseCase.ts, src/utils/translations.ts, src/webapp/components/app/App.tsx, src/webapp/logic/sheetBuilder.ts
- https://app.clickup.com/t/jvb57n
- Add translations for templates
=> [Feature] Translate templates

i18n/en.pot, i18n/es.po, i18n/fr.po, i18n/pt.po, i18n/ru.po, package.json, src/domain/helpers/ExcelBuilder.ts, src/domain/usecases/ImportTemplateUseCase.ts, src/utils/translations.ts, src/webapp/components/app/App.tsx, src/webapp/logic/settings.ts, src/webapp/logic/sheetBuilder.ts
- https://app.clickup.com/t/pbb925
- Check for permissions on unknown groups
=> [Fix] Check for permissions if metadata read is not granted

i18n/en.pot, i18n/es.po, i18n/fr.po, i18n/pt.po, i18n/ru.po, package.json, src/data/InstanceDhisRepository.ts, src/domain/helpers/ExcelBuilder.ts, src/domain/usecases/ImportTemplateUseCase.ts, src/utils/translations.ts, src/webapp/components/app/App.tsx, src/webapp/logic/settings.ts, src/webapp/logic/sheetBuilder.ts
- https://app.clickup.com/t/pzbv8m
- https://app.clickup.com/t/pzdbgq
- Add cartesian product to co, to build coc on events query
=> [Fix] Solve event query with multiple disaggregations

i18n/en.pot, i18n/es.po, i18n/fr.po, i18n/pt.po, i18n/ru.po, package.json, src/data/InstanceDhisRepository.ts, src/domain/entities/Template.ts, src/domain/helpers/ExcelBuilder.ts, src/domain/usecases/ImportTemplateUseCase.ts, src/utils/translations.ts, src/webapp/components/app/App.tsx, src/webapp/logic/settings.ts, src/webapp/logic/sheetBuilder.ts
- https://app.clickup.com/t/n37rbb
- Do not write all option possibilities on metadata tab
=> [Fix] Template generation with thousands of options

src/webapp/logic/sheetBuilder.ts
- If date was default value only an asterisk was appearing
=> [Fix] Properly translate dates assigned by program

i18n/en.pot, i18n/es.po, i18n/fr.po, i18n/pt.po, i18n/ru.po, package.json, src/data/InstanceDhisRepository.ts, src/data/templates/snakebite-annual-report/SnakebiteAnnualReport.01.ts, src/domain/entities/AppSettings.ts, src/domain/entities/DataForm.ts, src/test/mocks/server.ts, src/utils/codec.ts, src/webapp/components/settings/ProgramStageFilterDialog.tsx, src/webapp/logic/settings.ts, src/webapp/logic/sheetBuilder.ts, yarn.lock
* **Issue:** Closes https://app.clickup.com/t/1ht8ab3
- Propagate DE from other stages in current
- Add a new setting to select the external DEs
=> [Feature] Propagate DE from other stages in current

package.json, yarn.lock
* **Issue:** https://app.clickup.com/t/1j4n2qk
* **d2-ui-components**: Requires https://github.com/EyeSeeTea/d2-ui-components/pull/214
- Add overflow x
=> [Fix] Names too long

src/data/Dhis2RelationshipTypes.ts, src/data/Dhis2TrackedEntityInstances.ts
* **Issue:** https://app.clickup.com/t/1expwb4
- Paginate API call
=> [Fix] Paginate TEI endpoint

src/data/ExcelPopulateRepository.ts, src/domain/entities/DataPackage.ts, src/domain/helpers/ExcelReader.ts, src/domain/repositories/ExcelRepository.ts
* **Issue:** https://app.clickup.com/t/1ja8kjp
- Add row grouping
=> [Fix] Add row grouping

i18n/en.pot, i18n/es.po, i18n/fr.po, i18n/pt.po, i18n/ru.po, src/data/Dhis2Import.ts, src/data/Dhis2TrackedEntityInstances.ts, src/webapp/components/settings/DataSetDataElementsFilterDialog.tsx, src/webapp/components/settings/DuplicateDataElementsFilterDialog.tsx, src/webapp/components/settings/ProgramStageFilterDialog.tsx
- Fix import summary with async task
- Change title to Program Stage filter
- Remove reorder buttons where not possible to reorder fields
=> [Fix] Release feedback

src/data/Dhis2Import.ts, src/data/Dhis2TrackedEntityInstances.ts, src/data/ExcelPopulateRepository.ts, src/domain/helpers/ExcelReader.ts
- Refactor TEI code to remove nested loops during file reading
=> [Feature] Improve tracker performance with large files

src/domain/helpers/ExcelReader.ts
=> [Fix] Allow empty org units

package.json
=> Release 3.16.1

src/data/Dhis2TrackedEntityInstances.ts, src/domain/usecases/DownloadTemplateUseCase.ts
- Fix descendants OU filter for TEI
=> Fix TEI download for descendants

package.json, src/data/Dhis2TrackedEntityInstances.ts, src/data/InstanceDhisRepository.ts
- Add default ``CAPTURE`` mode
=> [Fix] Tracker import fails due no OU mode set

.env, public/app-config-default.json, public/app-config-who.json, public/app-config.json
=> update app config files

src/domain/usecases/DownloadTemplateUseCase.ts
* **Issue:** Closes https://app.clickup.com/t/865bznnvr
=> Allow translate codes for option sets in custom templates

i18n/en.pot, i18n/es.po, i18n/fr.po, i18n/pt.po, i18n/ru.po, package.json, src/domain/usecases/DownloadTemplateUseCase.ts, src/webapp/components/settings/TemplateListTable.tsx, src/webapp/components/template-selector/TemplateSelector.tsx, src/webapp/logic/sheetBuilder.ts, src/webapp/pages/download-template/DownloadTemplatePage.tsx
- Filter metadata COCs using dataset.orgunits/categoryOption.dates | orgUnits
- New setting to export templates using codes instead of names
- Allow translating codes for optionSets in custom templates
- Fix generation UI logic for custom templates
- Minor fix on build script
=> Release 3.20.2

src/data/Dhis2TrackedEntityInstances.ts, src/data/InstanceDhisRepository.ts, src/domain/entities/DataForm.ts, src/domain/entities/TrackedEntityInstance.ts, src/domain/helpers/ExcelReader.ts, src/domain/usecases/ImportTemplateUseCase.ts, src/test/mocks/server.ts, src/utils/files.ts, yarn.lock
* **Issue:** Closes https://app.clickup.com/t/865cqfwqq
File for testing with images in teis and events: [TestAfter.zip](https://github.com/EyeSeeTea/Bulk-Load/files/12030413/TestAfter.zip)
**Uploading 2 files in TEIS attributes**
=> allow images to be uploaded for attributes in TEIS

src/data/ExcelPopulateRepository.ts, src/webapp/logic/sheetBuilder.ts, src/webapp/pages/import-template/ImportTemplatePage.tsx
* **Issue:** Closes https://app.clickup.com/t/860r5dczv
Replace colon and whitespace from version name to avoid Microsoft Excel error.
from this
```xml
<definedNames>
<definedName name="Version: blank_template">'Sheet1'!$A$1</definedName>
</definedNames>
```
to this
```xml
<definedNames>
<definedName name="Version___blank_template">'Sheet1'!$A$1</definedName>
</definedNames>
```
=> remove whitespace and colon from version prefix

src/domain/entities/DataForm.ts, src/webapp/pages/import-template/ImportTemplatePage.tsx, src/webapp/utils/periods.js
* **Issue:** Closes https://app.clickup.com/t/860qmq6g4
Excel Template
Import Data
Import Result
=> add support for quarterly period

package.json, src/webapp/components/template-selector/TemplateSelector.tsx, src/webapp/pages/import-template/ImportTemplatePage.tsx, src/webapp/utils/template.ts, yarn.lock
* **Issue:** Closes https://app.clickup.com/t/860rtu5h4
- Update [d2-ui-components](https://github.com/EyeSeeTea/d2-ui-components/releases/tag/v2.7.0) to version 2.7.0
Run `yarn install` after pulling changes
**Download Template - switch OFF**
**Download Template - switch ON**
**Import Data - switch OFF**
**Import Data - switch ON**
=> allow OU tree to show shortName

package.json, yarn.lock
-   **Issue:** Closes https://app.clickup.com/t/860rub02b
No code change was needed on this repo, but in [d2-ui-components](https://github.com/EyeSeeTea/d2-ui-components/pull/232)
This can be tested in any dhis2 server.
=> update d2-ui-components to 2.7.0_beta.2

package.json, src/domain/usecases/DownloadTemplateUseCase.ts, src/webapp/components/template-selector/TemplateSelector.tsx, src/webapp/logic/sheetBuilder.ts, src/webapp/pages/download-template/DownloadTemplatePage.tsx, yarn.lock
* **Issue:** Closes https://app.clickup.com/t/860ryt00g
- Details about implementation https://github.com/EyeSeeTea/d2-ui-components/pull/233
Template with **short names** for org. units
Template with **display name** for org. units
=> use short names in templates

package.json, src/domain/helpers/ExcelReader.ts
- Ignore empty string values in custom templates
=> Release 3.23.1

package.json, src/domain/helpers/ExcelReader.ts, src/domain/usecases/ImportTemplateUseCase.ts, src/webapp/utils/period.ts, src/webapp/utils/periods.js
- Add support for financial period type
- Refactor boolean (yes/no) data values build
=> Release 3.23.2 - 2

src/webapp/components/theme-list/ThemePermissionsDialog.tsx
* **Issue:** Closes #86941jnhf [Error while trying to change permissions on bulk load](https://app.clickup.com/t/86941jnhf)
- Fix error while changing theme permissions and improve UX
[Screencast from 02-04-24 08:09:59.webm](https://github.com/EyeSeeTea/Bulk-Load/assets/49402898/ebb5f733-b61f-4c2e-b277-b8cc9f5ce78f)
=> Error while trying to change theme permissions on bulk load

i18n/en.pot, i18n/es.po, i18n/fr.po, i18n/pt.po, i18n/ru.po, src/domain/usecases/DownloadTemplateUseCase.ts, src/webapp/contexts/app-context.ts
* **Issue:** Closes https://app.clickup.com/t/8694ubx3x
#8694ubx3x
=> use default app namespace

package.json
* Include geometry property in event/tracker program import and download
* remove write permission for program stage generation
* check permissions for templates and autogenerated dataForms
* show multiple templates associated to one dataSet
=> release v3.24.0

src/data/Dhis2Import.ts, src/data/Dhis2RelationshipTypes.ts, src/data/Dhis2TrackedEntityInstances.ts, src/domain/entities/OrgUnit.ts, src/domain/entities/TrackedEntity.ts, src/domain/entities/TrackedEntityInstance.ts
* **Issue:** Closes https://app.clickup.com/t/8695xjma3
https://github.com/user-attachments/assets/2488942c-8ed9-45c0-9fcc-32c22b9a1ab1
#8695xjma3
=> [bugFix] program import error 

package.json, src/webapp/logic/Workbook.ts, src/webapp/logic/sheetBuilder.ts, yarn.lock
* **Issue:** Closes https://app.clickup.com/t/86991ktdr
For TEI attributes in program stages we're using excel functions like INDIRECT and ROW:
```
IFERROR(INDEX('${teiSheetName}'!$A$5:$ZZ$${maxTeiRows},MATCH(INDIRECT("B" & ROW()),'${teiSheetName}'!$A$5:$A$${maxTeiRows},0),MATCH(${colName}$${itemRow},'${teiSheetName}'!$A$5:$ZZ$5,0)),"");
```
however, excel does not support this formula as a shared formula, and throws the following error:
To work around this, I'm generating an individual formula for each row, which works in both Excel and LibreOffice.
Also check [this PR](https://github.com/EyeSeeTea/xlsx-populate/pull/23) for further details.
This PR depends on https://github.com/EyeSeeTea/xlsx-populate/pull/23. Once a beta version is released I'll update this PR again. …
=> use non shared formulas for TEI attributes in program stages sheets

src/webapp/logic/MetadataService.ts, src/webapp/logic/sheetBuilder.ts
* **Issue:** Closes #86955t567 [Improve ordering of category options in category option combos](https://app.clickup.com/t/86955t567)
- sort options in validation
=> Sort options in validation sheet

src/webapp/components/template-selector/TemplateSelector.tsx
* **Issue:** Closes #8699x9j22 [Create bulk load filters by TEAs with drop downs](https://app.clickup.com/t/8699x9j22)
- add no value option
=> add no value option for data filter

src/domain/entities/Template.ts
* **Issue:** Closes #8695743zk
- fix Template.ts file by adding missing `}`
=> fix Template.ts and remove unused functions
