src/webapp/logic/sheetImport.js

* **Issue:** Closes #91
- Add a type check to the string equals check
- We should improve this code in the future with our own excel reader

[Fix] Add check by type for categoryOptionCombos during import

---

i18n/en.pot
i18n/es.po
i18n/fr.po
src/domain/usecases/DownloadTemplateUseCase.ts
src/webapp/components/template-selector/TemplateSelector.tsx
src/webapp/pages/download-template/DownloadTemplatePage.tsx

* **Issue:** Closes #109 
- Add new pickers for populate and hide old pickers in programs
- Not sure about what extra validations should we add
- For dataSets, we could possibly check in populate the startDate and endDate of validations and enforce populate dates are between with ``min`` and ``max`` utilities.
- However to ensure state is always consistent we should clear ``populate`` dates when changing normal dates
Example of the check, but should be refactored into a utility method:
```tsx
<PopulateStartPicker
minDate={state.type === "dataSets" ? state.startDate : undefined}
maxDate={
state.type === "dataSets"
? moment.min(_.compact([state.endDate, state.populateEndDate]))
: state.populateEndDate
}
/>
<PopulateEndPicker
minDate={
state.type === "dataSets"
? moment.max( …
```

[Feature] Split date pickers

---

src/webapp/logic/dhisConnector.js
src/webapp/logic/sheetBuilder.js

* **Issue:** Closes #138 
How loadForm.action works:
- `formType = "SECTION"`: sections are ordered. Order of category combos within a section is indetermined. Within a category combo, the order of the data elements is kept from the original order in the section.
- Others: order of category combos is stablished by size of cocs associated to it (ASC). For the same number of cocs, the order is indeterminate. Within a category combo, data elements are sorted by name.
The original generated spreadsheet shows non-product cocs of on multi-category data elements, which is weird. So, I have some code to generate the cartesian product of category options (as data-entry does), but I've not committed it here, it's complex and needs some previous discussion because of the current behaviour.

Sort data elements to mimic dhis2 getForm

---

src/webapp/pages/import-template/ImportTemplatePage.tsx

* **Issue:** Closes #169
The original idea of changing the counts in the snackbar is not possible due to the weird responses returned by the POST events endpoint, which is, for the record (E: Events, DV: Datavalue):
- On events without ID (create): "imported: E+DV" 
- ON events with ID (update): "update: E"
To avoid confusion, we now simply hide the data values info in the summary (only for tracker programs)

Change summary tracker programs

---

package.json
src/webapp/logic/sheetBuilder.js
yarn.lock

* **Issue:** Closes #155
As we know from other projects, `categoryCombo.categoryOptionCombos` does not return an ordered collection, so we have to manually build the cartesian product of `category.categoryOptions` for every `categoryCombo.category`.
Data set `BU - minimum aggregated data_Annual_Disaggregated` contains data elements with multiple categories, so the cartesian product can be seen.
Note how some COCs have the category options swaped. That's because the COC was generated that way in the backend and since we are using indirect `=_ID` render, it's not fixable on our side. The COC should have the correct name in the backend. Data Administration -> Update category option combos does not fix these names.

[Data sets] Render sorted COCs for data elements disaggregation

---

src/data/Dhis2TrackedEntityInstances.ts
src/data/dhis2-uid.ts
src/domain/helpers/ExcelReader.ts

* **Issue:** Closes #186
- Allow empty TEI id -> generate randomly
- Generate a seed ID on import to avoid reusing UIDs with the same key name.

Refactor TEI ids (allow empty, don't reuse between imports)

---

src/data/Dhis2Import.ts
src/data/Dhis2TrackedEntityInstances.ts
src/domain/usecases/ImportTemplateUseCase.ts

* **Issue:** Closes #181
- Same than dataValues, override orgUnit from builder.
- Lateral change: on TEI import we have 3 requests: pre-TEI, post-TEI, events. Now we stop on the first unsuccessful request.

[import:TEI] Use organisation unit override

---

src/domain/entities/SynchronizationResult.ts
src/test/DownloadTemplatePage.spec.tsx
src/test/mocks/server.ts
src/webapp/logic/dhisConnector.js
src/webapp/pages/import-template/ImportTemplatePage.tsx
yarn.lock

- Detect error and attempt sending the events in chunks
- If there are no errors we don't paginate
Performance on a docker with a simple program but thousands of events:
- DHIS2 2.34 previous to the official fix (workaround: send in chunks of 99 events at a time)
- UI doesn't feel responsive (process takes too long it seems it has hung, but working behind the scenes)
- Bulk-Load tab on Chrome used 1.2GB of RAM memory itself
- Duplicate check (with 8k events already stored) elapsed a total of 5.38 minutes (with almost 100% CPU usage on Intel i7)
- Importing 20k events elapsed a total of 22 minutes (with CPU usage below 15%)
- Should we disable duplicate check when working with large amounts of events?
- The UI of the ``SyncSummary`` contains each network request independently, merging them …

[Fix] Send events in chunks

---

package.json
src/webapp/logic/sheetBuilder.js

* **Issue:** Closes https://app.clickup.com/t/dk3qqc
- Headers use named cells (`=_ID`) so we cannot add the ` *` suffix there. Therefore, we add the suffix to the name in the metadata sheet, as we do for compulsory program-stage data elements.
- This applies only to programs. Sheets for dataSets and tracker programs are unaffected (aren't they also compulsory?)

Show category combo as compulsory column on programs

---

src/data/ExcelPopulateRepository.ts

- Fix production-only issue with RichText cells
- We should properly address this in the future, the return types of RichTexts from ``xlsx-populate`` are not consistent and this is a workaround that we want not to face on other projects that use the library (predictors ie)

[Fix] Rich text detection on production builds

---

src/data/templates/generated-tracker-program/TrackerProgramGenerated.01.ts
src/webapp/logic/sheetBuilder.js

* **Issue:** Closes https://app.clickup.com/t/gd66jv, https://app.clickup.com/t/g56eey
- For program stages and relationship types, we now do, for example program stage: `Stage - 1-Valid Name of program stage`. This way we enforce a valid name and uniqueness. I think it's also handy to see the index of the tabs when you have many.
Tested with Excel 2019, COVID-19 RDT User experience, now the file opens without any warning.

Export tracker programs with stage/relationship sheet names validated

---

.env
i18n/en.pot
i18n/es.po
i18n/fr.po
i18n/pt.po
package.json
src/data/ConfigWebRepository.ts
src/domain/entities/AppSettings.ts
src/domain/entities/DataElementDisaggregated.ts
src/domain/usecases/DownloadTemplateUseCase.ts
src/webapp/components/settings/DataElementItem.ts
src/webapp/components/settings/DataSetDataElementsFilterDialog.tsx
src/webapp/components/settings/SettingsFields.tsx
src/webapp/components/template-selector/TemplateSelector.tsx
src/webapp/logic/settings.ts
src/webapp/logic/sheetBuilder.js
yarn.lock

* **Issue:** Closes: 
https://app.clickup.com/t/gd0mvn
https://app.clickup.com/t/gd0efp
Uses d2-ui-components beta: https://github.com/EyeSeeTea/d2-ui-components/pull/206
- Use dataSet sections:
- Branch logic: `const useDataSetSections = dataSet.formType === "SECTION" || !_(dataSet.sections).isEmpty();`
- `getDataElementsForSectionDataSet` refactored to use `dataSet.sections[].dataElements` and then the missing `dataSet.dataSetElements[].dataElement`. Note that previously only dataElements in sections where used.
- Data Set -> Data elements filter: Using new property in settings:  
```
"dataSetDataElementsFilter": {
"WxZRmtj4tr0": [
{
"id": "awsNtaiPxBR",
"categoryOptionComboId": "ivixWPWcOto"
}
]
}
```

Extend data set feature (use sections on generate + add setting data elements filter)

---

src/data/Dhis2Import.ts
src/domain/helpers/ExcelBuilder.ts
src/webapp/logic/dhisConnector.js
src/webapp/logic/sheetBuilder.js

Fixes:
Original issues created during the testing: https://app.clickup.com/t/gq7a4t
https://app.clickup.com/t/g709ua
https://app.clickup.com/t/g70a2w
https://app.clickup.com/t/h38v8p
https://app.clickup.com/t/h151jj
https://app.clickup.com/t/h56h73
> Some events are split in two (creating a sort of duplication) - See RDT User experience (28) excel file below
Some of the data elements belong to multiple program stages. For example, "Occupation" and "Other occupation" in the first and second tab. So, when exporting, you see the events for these data elements in both tabs. See COVID-19 RDT User experience (28)-exported.xlsx -> Now we match event.programStage with the current program stage sheet.
> When importing the Case Surveillance with test user, we get a "TEI not enrolled" although it …

COVID-19 refinement. Tracker fixes and improvements

---

i18n/en.pot
i18n/es.po
i18n/fr.po
i18n/pt.po
i18n/ru.po
package.json
src/data/Dhis2RelationshipTypes.ts
src/data/Dhis2TrackedEntityInstances.ts
src/data/InstanceDhisRepository.ts
src/data/templates/generated-tracker-program/TrackerProgramGenerated.03.ts
src/data/templates/index.ts
src/domain/entities/DataForm.ts
src/domain/entities/Geometry.ts
src/domain/entities/Template.ts
src/domain/entities/TrackedEntityInstance.ts
src/domain/helpers/ExcelBuilder.ts
src/domain/helpers/ExcelReader.ts
src/domain/usecases/DownloadTemplateUseCase.ts
src/test/mocks/server.ts
src/types/d2-api.ts
src/types/utils.ts
src/webapp/logic/sheetBuilder.ts
yarn.lock

* **Issue:** Closes https://app.clickup.com/t/1vqyygd
* **d2-api**: Requires https://github.com/EyeSeeTea/d2-api/pull/121 -> 1.10.2-beta.2
- Added new template v3 for tracker programs.
- Added column `geometry` in position C (hidden if no necessary -> featureType = NONE)
- Added entities `Coordinates` and `Geometry`
- Manual parsing of point/polygon (codec should not be used in an entity, no clear repo where to add it; JSON.parse still would need manual type checks).
NOTES:
- An error on the geometry field is an error that stops the process. Do we want instead to skip the cell and continue?
- The type of Polygon in D2 is `Array<Array<[Long, Lat]>>`. That, in fact, allows not one, but multiple polygons. However, the Tracker Capture UI (register & edit profile) only allows creating a single …

[Tracker programs] Add new geometry column (trackedEntityType.featureType)

---

src/data/Dhis2RelationshipTypes.ts
src/data/Dhis2TrackedEntityInstances.ts
src/data/ExcelPopulateRepository.ts

* **Issue:** Closes https://app.clickup.com/t/34bkxjk
- Versions tested: 2.37.7.1 and 2.38.1 (using d2-docker@development, needs Java 11)
- Import/export for:
- data sets
- event programs
- tracked programs (with a TEI/TEI relationships)
- [2.37] We were getting a Conflict 409 error on `/api/trackedEntityInstances` -> "Either Program or Tracked entity type should be specified". Solution: get all trackedEntityTypes and perform a request for each type.
- Force formulas string removal of the formula prefix (=): Not related to the DHIS version, but I was getting formulas like this `=_SOMEID`, which is wrong, `=` should be removed from the formula. That happened when trying to import dataSets with no modification of the spreadsheet so I am a bit confused as to why we had not encountered that …

Tests with 2.37 / 2.38

---

src/domain/helpers/ExcelReader.ts

* **Issue:** Closes https://app.clickup.com/t/34bkxjk
- `formatDhis2Value` expects that the code of the data value is set in property `optionId` for DE types boolean. That set was being done for type "rowTrackedEvent", but not for "row" and "cell" -> added.

Fix boolean parsing (adds optionId to types row/cell)

---

package.json
src/data/migrations/tasks/01.settings-permissions.ts

* **Issue:** Closes https://app.clickup.com/t/3kqq7th
- Change `migrations/tasks/01.settings-permissions.ts` so the setting for "all" access is enabled by default (not it was only if the user was a superadmin). 
- On already installed apps, it has no effect.

Grant all permissions for everyone on initial migration

---

src/webapp/logic/sheetBuilder.ts

https://github.com/EyeSeeTea/Bulk-Load/pull/284 introduced a bug. Due to the imperative implementation of `SheetBuilder.generate`, calls to `this.fillDataEntrySheet` cannot be called before `this.fillValidationSheet`, otherwise you get no validation object, and thus the data entry sheet gets no options/period/orgUnit selectors.

[fix] Recover options/period/orgUnits selectors on tab Data Entry

---

src/domain/usecases/DownloadTemplateUseCase.ts

* **Issue:** Closes https://app.clickup.com/t/865bg0p15
Filter raw metadata to exclude non-relevant category option combos.
`/api/dataSets/ID/metadata.json` returns categoryOptionCombos that may not be relevant for the data set. Here we filter out category option combos with categoryOptions not matching these conditions:
* categoryOption.startDate/endDate outside the startDate -> endDate interval
* categoryOption.orgUnit EMPTY or assigned to the dataSet orgUnits (intersected with the requested).

Filter metadata COCs using dataSet.orgUnits/categoryOption.dates|orgUnits

---

src/webapp/components/template-selector/TemplateSelector.tsx
src/webapp/pages/download-template/DownloadTemplatePage.tsx

* **Issue:** Closes https://app.clickup.com/t/860qhqq7e
- Permissions for custom template use the code, that's correct, the ID must be used for autogenerated forms. 
- The problem was with the matching templateCode/selectedId in the view, fixed. 
Validated by @idelcano  in https://portal-uat.who.int/dhis2

[Fix] Fix generation UI logic for custom templates

---

package.json
src/CompositionRoot.ts
src/data/FileD2Repository.ts
src/data/ImportSourceZipRepository.ts
src/domain/entities/FileResource.ts
src/domain/repositories/FileRepository.ts
src/domain/repositories/ImportSourceRepository.ts
src/domain/usecases/AnalyzeTemplateUseCase.ts
src/domain/usecases/ImportTemplateUseCase.ts
src/utils/files.ts
src/webapp/pages/import-template/ImportTemplatePage.tsx

* **Issue:** Closes https://app.clickup.com/t/865cm2c33
I tried to use d2-api, [but the domain is hardcoded to **"DOCUMENT"**](https://github.com/EyeSeeTea/d2-api/blob/master/src/api/files.ts#L43) and for this case it must be **"DATA_VALUE"**
Zip file for testing: [test-full.zip](https://github.com/EyeSeeTea/Bulk-Load/files/11886882/test-full.zip)
Docker: [docker.eyeseetea.com/eyeseetea/dhis2-data:2.36.11.1-sp-ip-test](docker.eyeseetea.com/eyeseetea/dhis2-data:2.36.11.1-sp-ip-test)
**Excel with filenames for before/after datavalue**
**Support for zip files**
**Tracker with images from zip file**

Add support for images

---

src/CompositionRoot.ts
src/data/Dhis2Events.ts
src/data/Dhis2TrackedEntityInstances.ts
src/data/ImportSourceNodeRepository.ts
src/data/InstanceDhisRepository.ts
src/domain/repositories/ImportSourceRepository.ts
src/domain/usecases/ImportTemplateUseCase.ts
src/scripts/import-multiple-files.ts

* **Issue:** Closes https://app.clickup.com/t/865ct86pm
Right now current implementation of the import data works with the [web File API](https://developer.mozilla.org/en-US/docs/Web/API/File). Since nodejs does not have support for that I tried to mimic but then I got different errors on the import process. I'm disabling TS check for that particular parameter and passing a buffer instead a File and it's working well. 
Script to upload multiple excel files can be executed using the following command:
```bash
npx ts-node src/scripts/import-multiple-files.ts \
--dhis2-url 'http://user:password@localhost:8080' \
--folder-path /home/bulkloadtemplates \
--results-path /home/bulkloadjsonresults
```
The `folder-path` must contains all the excel files to be imported.
The `results-path` can be an …

feat: upload teis and events in chunks

---

src/webapp/logic/sheetBuilder.ts

* **Issue:** Closes https://app.clickup.com/t/860rttvpf
- Reuse org. units that have been selected for the template in data elements with `valueType ORGANISATION_UNIT`
You can use the [program `AMR_GLASS_EGASP_PRE_INPUT_FILES`](https://dev.eyeseetea.com/who-dev-238/dhis-web-maintenance/index.html#/edit/programSection/program/SOjanrinfuG) for testing. Check that the program has the [`AMR_GLASS_EGASP_DET_LAB_ID` data element](https://dev.eyeseetea.com/who-dev-238/dhis-web-maintenance/index.html#/edit/dataElementSection/dataElement/J4c6Fxy7wQW). 
Template
Importing Data
Event in Capture App

Add org units selector for DE of type ORGANISATION_UNIT

---

src/domain/usecases/DownloadTemplateUseCase.ts
src/utils/files.ts
src/webapp/components/settings/TemplateEditDialog.tsx

* **Issue:** Closes https://app.clickup.com/t/860rp7h7k
We need to add support for files with extension `xlsm` because for NHWA Module 1 we need a dropdown list with multiple selection. Something that is not supported out of the box in excel, but can be enabled with macros.
Please download the new template with macros from the clickup issue
**Import Data Screen**
**Edit Custom Template Modal**

Support for excel files with macros

---

src/domain/helpers/ExcelReader.ts

* **Issue:** Closes https://app.clickup.com/t/862knky5u
Replacing the current formula for totals cells from: `=SUM(D9+D10+D17)` to `=IF(COUNT(E9,E10,E17)>0,SUM(E9,E10,E17),NA())`
With this we don't have by default the "0" value in all the cells that calculates totals. If there's no value in any of the cells that triggers the totals calculation the value for that cell will be `#N/A` (see screenshots section). That is going to be an empty value for bulk load therefore that cell will be ignored when user try to import the file.
New template and datasource json attached in the issue.

ignore empty string values in custom templates

---

src/webapp/utils/period.ts
src/webapp/utils/periods.js

* **Issue:** Closes https://app.clickup.com/t/8693jz670
Tested on [play demo 2.38.5.1](https://play.dhis2.org/2.38.5.1/dhis-web-maintenance/index.html#/edit/dataSetSection/dataSet/rsyjyJmYD4J) 
Template: [Expenditures.xlsx](https://github.com/EyeSeeTea/Bulk-Load/files/13981540/Expenditures.xlsx)
**Financial Year periods in template:**
**Import Preview**
**Import Result**
**Data Entry**

adding support for financial period type

---

src/domain/usecases/ImportTemplateUseCase.ts

* **Issue:** Required by https://app.clickup.com/t/8678yd6xd

[refactor] Refactor boolean (yes/no) data values build

---

src/webapp/components/template-selector/TemplateSelector.tsx

* **Issue:** Part one of [Redesign download template page](https://app.clickup.com/t/8694wfy5f)
- CU-8694wfy5f
Exchange filters position at Template Download Page, keeping expected functionality.
After selecting only one Data Model on configuration we keep the expected outcome:

Feat: redesign download template page filter order

---

src/webapp/logic/sheetBuilder.ts

* **Issue:** Closes https://app.clickup.com/t/86955vhn8
#86955vhn8
Right now in order to generate sheets for program stages the app check if the current user has read and write permissions to the program stage. In this PR I'm removing the write permission since we assume it's safe for the user to read the information. 
Asking @tokland for PR review in case this condition was added to cover any specific behaviour in the past.
- Create a user with bulk load access and only read permissions to any program stage.
- Download template with data using the `Populate template with data` option
- It should download an excel file with the TEI and program stages information.
**Program Stages sharing settings**
**Download template option**
**Excel file**

remove write permission for program stage generation

---

src/data/Dhis2TrackedEntityInstances.ts

* **Issue:** Closes https://app.clickup.com/t/8695w4j96
- In the new tracker the parameter for order events is `createdAt` (instead created) and the parameter to set the org. unit mode is `ouMode` (instead orgUnitMode)
**Download template**
**Excel file**
#8695w4j96

fix params for new tracker endpoint

---

src/data/Dhis2Import.ts

* **Issue:** Closes #8696ark8f
- updating response handling for `/tracker/jobs/<id>/report/`. Use response stats as fallback if `bundleReport.stats` is undefined.

used response stats as fallback if `bundleReport.stats` is undefined

---

README.md
src/data/templates/msf/MSFModule1.01.ts
src/scripts/import-multiple-files.ts

* **Issue:** Closes https://app.clickup.com/t/8697qpqp6
- There was a missing type that was generating an error while executing the import files from script. 
```bash
TSError: ⨯ Unable to compile TypeScript:
src/data/templates/msf/MSFModule1.01.ts:347:21 - error TS2322: Type 'string' is not assignable to type 'never'.
```
Also I've added some instructions to the readme on how to execute the script.
#8697qpqp6

add explicit type to array, update readme with script instructions

---

src/domain/helpers/ExcelBuilder.ts

* **Issue:** Closes https://app.clickup.com/t/8697n6kzy
- Add program stage ID to dataStore in bulk-load/BULK_LOAD_SETTINGS to `programStagePopulateEventsForEveryTei` object:
https://github.com/user-attachments/assets/ce926692-3963-4a10-b8fe-3695609c1673
#8697n6kzy

fix: teiId rowStart bug in program stage sheets

---

src/data/Dhis2RelationshipTypes.ts
src/data/Dhis2TrackedEntityInstances.ts
src/data/InstanceDhisRepository.ts
src/domain/entities/DhisDataPackage.ts
src/domain/entities/TrackedEntity.ts

* **Issue:** Closes #8697re161
- updated response handling for `/tracker/events` and `/tracker/trackedEntities` to use a fallback (instances || (events/trackedEntities) || []
- updated `/tracker/events` payload to not include `programStage` when it is null
- use ouMode for calls to /tracker/trackedEntities
- v38-40: compatible with ouMode only
- v41: compatible with ouMode and orgUnitMode. Can't send both on v41 so I used ouMode for all
- v41: error when programStage is empty

fix errors in export event program and tracker program

---

src/data/Dhis2Events.ts
src/data/Dhis2Import.ts
src/data/Dhis2RelationshipTypes.ts
src/data/Dhis2TrackedEntityInstances.ts
src/data/InstanceDhisRepository.ts
src/webapp/logic/sheetBuilder.ts

* **Issue:** Closes https://app.clickup.com/t/8697qpqp6
- Parse `yes/no` values to `true/false` to avoid validation errors with boolean attributes
**UPDATE 2025-02-09**
- Remove comments in program stages to avoid error in excel:
```
we found a problem with some content in excel do you want us to recover as much as we can
```
Right now the library is generating comments with this xml structure:
```xml
<comment ref="E2" authorId="0">
<text>
<t>TESTS</t>
</text>
</comment>
```
and it looks like the "right" xml for excel should be:
```xml
<comment ref="E2" authorId="0">
<text>
<r>
<rPr>
<sz val="10"/>
<color indexed="81"/>
<rFont val="Tahoma"/>
<family val="2"/>
</rPr>
<t>TESTS</t>
</r>
</text>
</comment>
```
I'm removing the comments, but when we have more time we can check if adding[ this …

set enrollment for events, remove optionId validation

---

src/data/Dhis2TrackedEntityInstances.ts
src/data/ExcelPopulateRepository.ts
src/data/InstanceDhisRepository.ts
src/data/templates/snakebite-annual-report/SnakebiteAnnualReport.01.ts
src/domain/entities/DataForm.ts
src/domain/entities/DataPackage.ts
src/domain/entities/DhisDataPackage.ts
src/domain/entities/Template.ts
src/domain/helpers/ExcelBuilder.ts
src/domain/helpers/ExcelReader.ts
src/domain/usecases/DownloadTemplateUseCase.ts
src/domain/usecases/ImportTemplateUseCase.ts
src/types/utils.ts
src/webapp/pages/import-template/ImportTemplatePage.tsx

* **Issue:** Closes #86993u0x8 [Make TEI ID available in Program Stages tabs by default](https://app.clickup.com/t/86993u0x8)
- refactored DataPackage - discriminated unions
- DataPackage was heavily used in `ExcelBuilder` and `ExcelReader`. To avoid extending the scope to import/export flows, `Template` models were created.  
- removed unused `comment` prop from DataPackage type "dataSets" 
Note: bug introduced in #327 where `trackedEntityInstance` was renamed only during mapping. It was an optional prop so there were no complaints from typescript.
https://github.com/user-attachments/assets/cf0c25e2-ab4d-4b00-ab89-80289bfcaeff
tested: import/export tracker programs and datasets

Fix: missing template tei ids
